package commons;

public enum BrowserList {
	FIREFOX, CHROME, EDGE, SAFARI, OPERA, CHROME_HEADLESS, EDGE_HEADLESS, FIREFOX_HEADLESS, FIREFOX_ADDEX, CHROME_ADDEX,
	EDGE_ADDEX, CHROME_DEMO_LOG, FIREFOX_DEMO_LOG, EDGE_DEMO_LOG, FIREFOX_LOG_CONSOLE, CHROME_LOG_CONSOLE,
	EDGE_LOG_CONSOLE, CHROME_DEMO_LOG_LEVEL, FIREFOX_DEMO_LOG_LEVEL, EDGE_DEMO_LOG_LEVEL;
}
